name: do-fastapi-simple-dev
region: ams
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: api
    match:
      path:
        prefix: /api/v1
  - component:
      name: website
    cors:
      allow_origins:
      - prefix: https://internal.example-app.com
    match:
      path:
        prefix: /
services:
- environment_slug: python
  github:
    branch: dev
    deploy_on_push: true
    repo: skipperkongen/do-fastapi-simple
  http_port: 8000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: api
  run_command: fastapi run main.py --root-path /api/v1
  source_dir: /backend
static_sites:
- environment_slug: html
  github:
    branch: dev
    deploy_on_push: true
    repo: skipperkongen/do-fastapi-simple
  name: website
  source_dir: /frontend/
  build_command: npm install && npm run build
  output_dir: /dist